# Generated by Django 5.0.3 on 2024-05-12 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_clothingitem_image_alter_clothingitem_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_clothing_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorited_by', to='core.clothingitem'),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_outfit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorited_by', to='core.outfit'),
        ),
    ]
